---
title: "Decisions on ant and alkaloid data"
author: "Ivan Prates"
date: "6/14/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##This file presents notes on decisions about ant and alkaloid data, as follows:

1. We considered _Aphaenogaster_ ants to have alkaloids because they have anabaseine, which is analogous to the frog alkaloid noranabasamine (Daly _et al_., 2005).

2. Alkaloids were detected in _Paratrechina steinheili_ (Saporito _et al_., 2004) and _P. amblyops_ (Clark _et al_., 2005). These two species are now allocated in the genus _Nylanderia_ (La Polla _et al_., 2010). As a result, no _Paratrechina_ (as currently recognized) were included in our study.

3. _Carebarella_, found to contain HTX (Jones _et al_., 2012), is now within _Solenopsis_ (Pacheco and Mackay, 2013).

4. There does not appear to be a deohy-PTX class, but there is a deoxy-hPTX class (Daly _et al_., 2005). deohy-PTX seems to have been listed in error in Saporito _et al_. (2007).

5. Alkaloids 235B, 235B', and 235B'' were treated as 235B, following Daly _et al_. (2005).

6. Alkaloids 195A, cis-195A, and trans-195A were treated as 195A, following Daly _et al_. (2005).

7. Alkaloid "321", itself detected in a single site, was included. Although it is no clear whether it represents alkaloid 321A, B, C, D, or E, this chemical is not present in any other site.

8. Alkaloid "325", itself detected in a single site, was excluded. The reason for this exclusion is that it is not clear whether it represents alkaloids 325 A, B, or C, which are present in other sites.

9. There seems to be no 207H listed for any sampled site in the Supplementary Information of Saporito _et al_. (2007), even if there is in the main text. The total number of alkaloids listed by Saporito _et al_. (2007) therefore seems to be 231 and not 232.

10. Daly _et al_. (2005) report 237C (5,6,8-I) to be of ant origin, but Saporito _et al_. (2009) do not. Following Saporito _et al_. (2009), we do not treat 5,6,8-I as being of ant origin.

11. Clark _et al_. (2005) found alkaloid 225C in an ambiguous mixture of _Camponotus_ and _Pachycondyla_ ants. Therefore, we conservatively do not consider them to be alkaloid-bearing ants. 

12. Tricyclics were not excluded from analyses restricted to ant alkaloids because this class was found in African _Myrmicaria_ ants (Schroder _et al_., 1996).
